[tool.poetry]
name = "fastapi-realworld-api"
version = "0.1.0"
description = "Exemplo de projeto utilizado no mundo real"
authors = ["Douglas <douglaspands@gmail.com>"]
readme = "README.md"
packages = [{include = "server"}]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.3"
sqlmodel = "^0.0.17"
uvicorn = {extras = ["standard"], version = "^0.29.0"}
pydantic-settings = "^2.2.1"
asyncio = "^3.4.3"
gunicorn = "^22.0.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.4.2"
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
mypy = "^1.10.0"
isort = "^5.13.2"
black = "^24.4.2"
httpx = "^0.27.0"
rich = "^13.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"

[tool.poetry.scripts]
server = 'scripts.poetry:run_server'
server_debug = 'scripts.poetry:run_server_debug'
