apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - fastapi-secret.yaml
  - fastapi-configmap.yaml
  - fastapi-deployment.yaml
  - fastapi-hpa.yaml
  - fastapi-service.yaml
  - fastapi-ingress.yaml
