apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: job-secret
  namespace: realworld
data:
  db_url: cG9zdGdyZXNxbCtwc3ljb3BnOi8vZmFzdGFwaV91c2VyOjEyMzQ1NkBkYi1zZXJ2aWNlLnJlYWx3b3JsZC5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyL2Zhc3RhcGkK
